### ISSUE TITLE
Abandon dynamic loading for browser contexts

### ISSUE THREAD

**Issue by nebulon42** [mapnik/mapnik-reference#116]
I'm currently attempting browserification of Carto and mapnik-reference will have to change too to support it. Dynamic loading i.e. using require with variables is not supported in a browser context.

So we would have to move to requiring all versions explicitly. This has the obvious downside that all versions have to be loaded, which may not be necessary outside of a browser context. Another possibility would be to detect if being in a browser context (e.g. http://stackoverflow.com/a/31090240) and only then requiring all the versions.

I can provide a patch, but the general direction would have to be clarified first.
Thoughts?

**Comment by nebulon42** [comment]
See also https://github.com/mapnik/mapnik-reference/pull/111#issuecomment-161049168.

**Comment by springmeyer** [comment]
Dynamic loading I added in https://github.com/mapnik/mapnik-reference/pull/94 because I found it critical to avoid `require` slowdowns (which added to the lag of TileMill and Mapbox Studio Classic opening). So we need to keep that functionality - and extend it by landing #109. So, for browser support I think some kind of custom detection and different logic is okay. Is that something you can work on?

**Comment by nebulon42** [comment]
Yes, I'll give it a try.
